export const Gents={
    title:"Gents Fashion",
    image1:"assets/Men/1.jpg",
    image2:"assets/Men/2.jpg",
    image3:"assets/Men/3.jpg",
    image4:"assets/Men/4.jpg",
    image5:"assets/Men/5.jpg",
    image6:"assets/Men/6.jpg",
    price1:"559 INR",
    price2:"559 INR",
    price3:"559 INR",
    price4:"559 INR",
    price5:"559 INR",
    price6:"559 INR",
}
export const Ladies={
    title:"Ladies Fashion",
    image1:"assets/Woman/1.jpg",
    image2:"assets/Woman/2.jpg",
    image3:"assets/Woman/3.jpg",
    image4:"assets/Woman/4.jpg",
    image5:"assets/Woman/5.jpg",
    image6:"assets/Woman/6.jpg",
    image7:"assets/Woman/7.jpg",
    image8:"assets/Woman/8.jpg",
    price1:"1599 INR",
    price2:"1599 INR",
    price3:"559 INR",
    price4:"559 INR",
    price5:"559 INR",
    price6:"559 INR",
    price7:"399 INR",
    price8:"499 INR",
}